name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        img: this-image
      run: |
        tag=$(date +%s)
        docker build . -t ${img}:${tag}
        docker run --rm -i ${img}:${tag} npm run lint
